# Generated by Django 5.2.8 on 2025-11-25 16:32

import django.db.models.deletion
from django.db import migrations, models


def set_default_category(apps, schema_editor):
    Category = apps.get_model('product', 'Category')
    Product = apps.get_model('product', 'Product')
    default_category, _ = Category.objects.get_or_create(
        name='Default kategoriya',
        defaults={
            'is_active': True,
        },
    )
    Product.objects.filter(category__isnull=True).update(category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriya',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='Kategoriya'),
        ),
        migrations.RunPython(set_default_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='Kategoriya'),
        ),
    ]
