# Generated by Django 5.2.8 on 2025-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(verbose_name='Umumiy narx'),
        ),
    ]
